### ISSUE TITLE
With the newest micro, this does nothing

### ISSUE THREAD

**Issue by luminarious** [joakimbeng/micro-compress#2]
This is my test index.js:
```
const {send, json} = require('micro')
const compress = require('micro-compress')

module.exports = compress({threshold: 0}, async (req, res) => {
	const body = `What is Lorem Ipsum?`
	send(res, 200, body)
})
```

**Comment by joakimbeng** [comment]
I totally missed this issue...

I've investigated it now using your code and running micro with: `DEBUG=* micro` which yields the following when doing a request:

```
micro: Accepting connections on port 3000
  compression undefined not compressible +0ms
  compression no compression: filtered +0ms
```

And when looking into micro's code, specifically the [`send` function](https://github.com/zeit/micro/blob/master/lib/index.js#L28), you can see that the `Content-Type` header is not set for strings. By changing the `body` to an object the problem is solved.
